### ISSUE TITLE
Issue when printing

### ISSUE THREAD

**Issue by latelylk** [glatteis/poem-printer#1]
It appears I'm also having an issue with printing. The html and png generated by the server appear fine, but what the printer actually spews out does not:

https://imgur.com/a/l9JWyJ4

So far I've checked the connection and baud rate. simplePrint works fine, it's only an issue when trying to print a poem.

Any help is appreciated.

**Comment by linusheck** [comment]
Which model of thermal printer do you have? Could be that the serial
instructions are different.

Pierce <notifications@github.com> schrieb am Di., 24. Dez. 2019, 07:28:

**Comment by latelylk** [comment]
I'm using the adafruit 597 Mini Thermal Receipt Printer which I purchased through Amazon.

**Comment by linusheck** [comment]
Okay, this is exactly the model I have too. I also had this problem, not sure what fixed it.
On which voltage are you running it (also see the debug printout, when you plug it in while you press the top button)? Which exact ESP are you using? Maybe you could try printing another image from an arduino example, see how that turns out.
As I can see on your image, sometimes it does the correct thing. It's probably some very fixable hardware/software issue.

**Comment by latelylk** [comment]
> On which voltage are you running it (also see the debug printout, when you plug it in while you press the top button)?

9V 2A power supply. Debug printout here: https://imgur.com/a/GDGzXkQ

> Which exact ESP are you using?

[This one](https://www.amazon.com/dp/B010N1SPRK) - ESP8266 NodeMCU

> Maybe you could try printing another image from an arduino example, see how that turns out.

I'll try this when I get the chance. I know the simplePrint works (at least for a line as that's all I've tested), this only happens when trying to print the poem.

> As I can see on your image, sometimes it does the correct thing. It's probably some very fixable hardware/software issue.

Hopefully it can be fixed.

**Comment by linusheck** [comment]
Hmm, this all looks good.

Am Do., 26. Dez. 2019 um 05:48 Uhr schrieb Pierce <notifications@github.com

**Comment by linusheck** [comment]
Hey, do you still have this issue? I can try to fix it with you.

**Comment by latelylk** [comment]
I still have the issue, but I unfortunately do not have the time to tinker with it. Closing the issue for now.

**Comment by linusheck** [comment]
Comment when you have time, I could walk through my setup with you and see
what we are doing different :)

Pierce <notifications@github.com> schrieb am Sa., 14. März 2020, 03:11:
